<a href="https://colab.research.google.com/github/adepril/Covid19-Evolution/blob/main/CovidRaceBarAnimation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install bar_chart_race

Requirement already satisfied: bar_chart_race in /usr/local/lib/python3.7/dist-packages (0.1.0)
Requirement already satisfied: matplotlib>=3.1 in /usr/local/lib/python3.7/dist-packages (from bar_chart_race) (3.2.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.7/dist-packages (from bar_chart_race) (1.1.5)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.1->bar_chart_race) (2.8.1)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.1->bar_chart_race) (1.19.5)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.1->bar_chart_race) (1.3.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.1->bar_chart_race) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.1->bar_chart_race) (0.10.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24->bar_chart_race) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=3.1->bar_chart_race) (1.15.0)

In [ ]:
import pandas as pd
import bar_chart_race as bcr

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
df.head()

  Province/State Country/Region       Lat  ...  5/26/21  5/27/21  5/28/21
0            NaN    Afghanistan  33.93911  ...    67743    68366    69130
1            NaN        Albania  41.15330  ...   132244   132264   132285
2            NaN        Algeria  28.03390  ...   127646   127926   128198
3            NaN        Andorra  42.50630  ...    13671    13682    13693
4            NaN         Angola -11.20270  ...    33338    33607    33944

[5 rows x 497 columns]

In [ ]:
df = df.drop(columns=["Lat","Long"])

In [ ]:
# nouvelle colonne "Location" qui combine "Province/State" et "Country/Region"
df['Location'] = df[['Province/State','Country/Region']].apply(lambda x: ', '.join(x.dropna()),axis=1)
df.sample(3)

    Province/State Country/Region  1/22/20  ...  5/27/21  5/28/21         Location
90          Yunnan          China        1  ...      352      352    Yunnan, China
48         Nunavut         Canada        0  ...      647      648  Nunavut, Canada
165            NaN         Latvia        0  ...   132258   132612           Latvia

[3 rows x 496 columns]

In [ ]:
df = df.drop(columns=["Province/State", "Country/Region"])

In [ ]:
# mettre la colonne 'Location' en premiere position
cols = list(df.columns)
cols = [cols[-1]] + cols[:-1]
df = df[cols]

In [ ]:
# transposer ligne/colonne pour que le pays soit le nom de la conne et que chaque date soit une ligne
df_transposed = df.T
df_transposed

                  0        1        2    ...    273     274       275
Location  Afghanistan  Albania  Algeria  ...  Yemen  Zambia  Zimbabwe
1/22/20             0        0        0  ...      0       0         0
1/23/20             0        0        0  ...      0       0         0
1/24/20             0        0        0  ...      0       0         0
1/25/20             0        0        0  ...      0       0         0
...               ...      ...      ...  ...    ...     ...       ...
5/24/21         66275   132215   127107  ...   6662   93279     38696
5/25/21         66903   132229   127361  ...   6670   93428     38706
5/26/21         67743   132244   127646  ...   6688   93627     38819
5/27/21         68366   132264   127926  ...   6696   93947     38854
5/28/21         69130   132285   128198  ...   6723   94430     38918

[494 rows x 276 columns]

In [ ]:
# la fonction transpose a mis les pays dans la premiere ligne
# on veut que ce soit le nom des colonnes
df_transposed.columns = df_transposed.iloc[0].to_list()
df_transposed.columns

Index(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia',
       'Australian Capital Territory, Australia', 'New South Wales, Australia',
       ...
       'United Kingdom', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela',
       'Vietnam', 'West Bank and Gaza', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype='object', length=276)

In [ ]:
df_transposed

          Afghanistan  Albania  Algeria  ...  Yemen  Zambia  Zimbabwe
Location  Afghanistan  Albania  Algeria  ...  Yemen  Zambia  Zimbabwe
1/22/20             0        0        0  ...      0       0         0
1/23/20             0        0        0  ...      0       0         0
1/24/20             0        0        0  ...      0       0         0
1/25/20             0        0        0  ...      0       0         0
...               ...      ...      ...  ...    ...     ...       ...
5/24/21         66275   132215   127107  ...   6662   93279     38696
5/25/21         66903   132229   127361  ...   6670   93428     38706
5/26/21         67743   132244   127646  ...   6688   93627     38819
5/27/21         68366   132264   127926  ...   6696   93947     38854
5/28/21         69130   132285   128198  ...   6723   94430     38918

[494 rows x 276 columns]

In [ ]:
# il faut supprimer la premiere ligne que est le nom des pays
df_transposed = df_transposed.iloc[1:]
df_transposed

        Afghanistan Albania Algeria  ... Yemen Zambia Zimbabwe
1/22/20           0       0       0  ...     0      0        0
1/23/20           0       0       0  ...     0      0        0
1/24/20           0       0       0  ...     0      0        0
1/25/20           0       0       0  ...     0      0        0
1/26/20           0       0       0  ...     0      0        0
...             ...     ...     ...  ...   ...    ...      ...
5/24/21       66275  132215  127107  ...  6662  93279    38696
5/25/21       66903  132229  127361  ...  6670  93428    38706
5/26/21       67743  132244  127646  ...  6688  93627    38819
5/27/21       68366  132264  127926  ...  6696  93947    38854
5/28/21       69130  132285  128198  ...  6723  94430    38918

[493 rows x 276 columns]

In [ ]:
# labiliser l'index avec le nom "Date"
df_transposed.index.names = ["Date"]
df_transposed

        Afghanistan Albania Algeria  ... Yemen Zambia Zimbabwe
Date                                 ...
1/22/20           0       0       0  ...     0      0        0
1/23/20           0       0       0  ...     0      0        0
1/24/20           0       0       0  ...     0      0        0
1/25/20           0       0       0  ...     0      0        0
1/26/20           0       0       0  ...     0      0        0
...             ...     ...     ...  ...   ...    ...      ...
5/24/21       66275  132215  127107  ...  6662  93279    38696
5/25/21       66903  132229  127361  ...  6670  93428    38706
5/26/21       67743  132244  127646  ...  6688  93627    38819
5/27/21       68366  132264  127926  ...  6696  93947    38854
5/28/21       69130  132285  128198  ...  6723  94430    38918

[493 rows x 276 columns]

In [ ]:
# on ne s'interresse qu'aux pays suivant
cols = ["France","US","Germany","Italy","United Kingdom","Brazil","Russia","Spain"]
df_subset = df_transposed[cols]
df_subset

          France        US  Germany  ...    Brazil   Russia    Spain
Date                                 ...
1/22/20        0         1        0  ...         0        0        0
1/23/20        0         1        0  ...         0        0        0
1/24/20        2         2        0  ...         0        0        0
1/25/20        3         2        0  ...         0        0        0
1/26/20        3         5        0  ...         0        0        0
...          ...       ...      ...  ...       ...      ...      ...
5/24/21  5550143  33143662  3659990  ...  16120756  4952412  3647520
5/25/21  5552977  33166418  3662568  ...  16194209  4960174  3652879
5/26/21  5564217  33190470  3667041  ...  16274695  4968421  3657886
5/27/21  5578150  33217995  3673990  ...  16342162  4977332  3663176
5/28/21  5588981  33239963  3680159  ...  16391930  4986458  3668658

[493 rows x 8 columns]

In [ ]:
# creer un datafrane où chaque ligne s'aditionne à la précédente
# mettre toutes les types est numeric 
df_cum_sum = df_subset.cumsum()
df_cum_sum = df_cum_sum.apply(pd.to_numeric)

In [ ]:
# mettre l'index (Date) en type datetime
df_cum_sum.index = pd.to_datetime(df_cum_sum.index)

In [ ]:
# plotting
bcr.bar_chart_race(
    df_cum_sum,
    title="Evolution du Covid19",
    interpolate_period=True,  
    period_fmt="%b %-d, %Y"
)
# filename="covid.mp4"

Evolution du Covid19 en Chine

In [ ]:
# labiliser l'index avec le nom "Date"
df_transposed.index.names = ["Date"]
df_transposed

In [ ]:
# chercher les colonnes qui ont le nom "chine" dans leur nom complet
cols = df_transposed.columns.to_list()
chine = [col for col in cols if 'China' in col]
chine

In [ ]:
# on ne s'interresse qu'aux pays suivant
df_subset = df_transposed[chine]
df_subset

In [ ]:
# creer un datafrane où chaque ligne s'aditionne à la précédente
# mettre toutes les types est numeric 
df_cum_sum = df_subset.cumsum()
df_cum_sum = df_cum_sum.apply(pd.to_numeric)

In [ ]:
# creer un datafrane où chaque ligne s'aditionne à la précédente
# mettre toutes les types est numeric 
df_cum_sum = df_subset.cumsum()
df_cum_sum = df_cum_sum.apply(pd.to_numeric)

In [ ]:
# plotting
bcr.bar_chart_race(
    df_cum_sum,
    title="Evolution du Covid19 en Chine",
    n_bars=8,
    interpolate_period=True,  
    period_fmt="%b %-d, %Y"
)